PAYMENT AND REGISTRATION PAGE
dscnitrourkela/project-udon pull request #19
Opened 2024-03-13 16:01 UTC by babitarit

2024-03-13 20:17 UTC, starkjay21 commented
Please take care of commit message standards

2024-03-14 18:01 UTC, ashutosh-rath02 commented
@babitarit Please change your PR titile.

2024-03-14 18:03 UTC, ashutosh-rath02 commented
![image](https://github.com/dscnitrourkela/project-udon/assets/85403534/65781489-6a8f-458e-b361-af8d0ff89283)
Please fix this.

2024-03-18 14:17 UTC, Shurtu-gal requested changes
@babitarit as can be seen [here](https://github.com/dscnitrourkela/project-udon/actions/runs/8320332803/job/22787358400?pr=19#step:7:16) `HeroText` has been changed to `HeroText1`.

Please modify it in your code.

2024-03-18 20:16 UTC, babitarit commented
@Shurtu-gal after doing => HeroText has been changed to HeroText1 still deploy error exist

2024-03-18 20:31 UTC, Shurtu-gal commented
> @Shurtu-gal after doing => HeroText has been changed to HeroText1 still deploy error exist

@babitarit I believe it is working.

2024-03-23 16:22 UTC, ashutosh-rath02 requested changes

2024-03-23 16:22 UTC, ashutosh-rath02 commented on src/components/shared/Register/Final.jsx
> +						Payment method we have
Move text to content

2024-03-23 16:22 UTC, ashutosh-rath02 commented on src/components/shared/Register/Register.jsx
> +			</div>
`Payment.jsx` and `Register.jsx` seems to have same structure, create a reusable component and use it instead following good practices.

2024-05-04 11:32 UTC, Shurtu-gal commented
closing as done

2024-05-04 11:32 UTC, closed without merging