Faq
dscnitrourkela/project-udon pull request #27
Opened 2024-04-02 19:23 UTC by praptippradhan

2024-04-04 06:47 UTC, jayeshxn requested changes
Please complete the requested changes.

2024-04-04 06:47 UTC, jayeshxn commented on src/components/Gallery/gallery.jsx
make different PR for this component

2024-04-04 06:47 UTC, jayeshxn commented on src/components/Gallery/gallery.jsx
> +						}}>
change to tailwind css

2024-04-04 06:47 UTC, jayeshxn commented on src/components/Gallery/galleryMain.jsx
> +					textShadow: '4.608px 4.608px 0px #000',
use tailwind

2024-04-04 06:58 UTC, jayeshxn commented
LGTM🚀

2024-04-04 07:00 UTC, jayeshxn approved these changes

2024-04-04 07:00 UTC, merged

2024-04-15 13:04 UTC, Shurtu-gal commented
@all-contributors add @praptippradhan for code and add @jayeshxn for review.

2024-04-15 13:05 UTC, Shurtu-gal commented
@all-contributors 
please add @praptippradhan for code
please add @jayeshxn for review.