feat: adding footer
dscnitrourkela/project-udon pull request #8
Opened 2024-03-06 13:32 UTC by starkjay21

2024-03-06 16:13 UTC, Shurtu-gal requested changes

2024-03-06 16:13 UTC, Shurtu-gal commented on src/components/shared/marginals/footer.jsx
> +				<div className='w-full flex justify-end'>
A gap can be added.
![image](https://github.com/dscnitrourkela/project-udon/assets/100484401/ec41fe23-0ab0-4c94-a594-65989dea4df5)

2024-03-09 07:48 UTC, starkjay21 commented
@Shurtu-gal Please review!

2024-03-09 10:26 UTC, merged

2024-03-10 07:15 UTC, Shurtu-gal commented
@all-contributors please add @starkjay21 for code.