feat:Added NavBar Section
dscnitrourkela/project-udon pull request #9
Opened 2024-03-06 17:32 UTC by anmol5936

2024-03-07 13:08 UTC, Shurtu-gal requested changes

2024-03-07 13:08 UTC, Shurtu-gal commented on src/components/shared/typography/NavButton.jsx
The typographies for both these are already present and can be used as https://github.com/dscnitrourkela/project-udon/blob/4bc920369698d73c8230cdbe747e853a9f67cc81/src/pages/playground.jsx#L15-L16

2024-03-07 13:08 UTC, Shurtu-gal commented on src/components/NavBar.jsx
Can be shifted inside `./shared`.

2024-03-07 13:08 UTC, Shurtu-gal commented on src/components/NavBar.jsx
> +			<div
Usage of proper semantic elements should be done.

2024-03-07 13:08 UTC, Shurtu-gal commented on src/components/NavBar.jsx
> +						<NavElement key={index} className='mx-[55px]'>
Make use of `<Link />` components and put text inside that.

2024-03-08 10:48 UTC, Shurtu-gal requested changes
![image](https://github.com/dscnitrourkela/project-udon/assets/100484401/32a95acd-895e-4868-8d5a-cc352e35149d)

Links can still fit in this size I suppose.

2024-03-08 10:48 UTC, Shurtu-gal commented on src/assets/images/menu.png
Use a hamburger instead of images as was done in hacknitr.

2024-03-08 10:48 UTC, Shurtu-gal commented on src/components/shared/NavBar.jsx
> +				className='navbar flex justify-between items-center opacity-53 bg-hard-light bg-center bg-cover h-[73.8px] overflow-hidden'
Instead of mentioning height try to do it through padding.

Same with padding left and right instead of margin.

2024-03-08 10:48 UTC, Shurtu-gal commented on src/components/shared/NavBar.jsx
> +				<div className='ml-[56.6px]'>Logo</div>
Try use padding in parent div. Furthermore where is the responsiveness as padding is too much for mobile screens.

2024-03-08 10:48 UTC, Shurtu-gal commented on src/components/shared/NavBar.jsx
> +						<Text as='button' className={`mr-[56.6px] hamburger-icon`} onClick={toggleNav} variant='navButton'>
Why not use button itself?

Like what's the point of using `Text` here.

2024-03-08 10:48 UTC, Shurtu-gal commented on src/components/shared/NavBar.jsx
> +						<Text
Make a shared component with multiple variants like was discussed with `cva`.

2024-03-10 09:48 UTC, Shurtu-gal commented on src/assets/images/menu.png
@anmol5936 if you are not using it it can be removed.

2024-03-10 11:05 UTC, Shurtu-gal requested changes
Remove the unneeded images.

2024-03-10 11:05 UTC, Shurtu-gal commented on src/components/shared/NavBar.jsx
> +						<button className={`mr-[56.6px] hamburger-icon`} onClick={toggleNav}>
Something like `cn('<normal_classes>', isOpen ? 'opening styles' : 'closed styles')`

2024-03-10 11:05 UTC, Shurtu-gal commented on src/components/shared/NavBar.jsx
> +		if (isMobile) {
Don't try to do this use state instead as mentioned below.

2024-03-10 11:05 UTC, Shurtu-gal commented on src/components/shared/NavBar.jsx
> +		const handleResize = () => {
This can be handled by media query also I believe.

2024-03-10 11:15 UTC, Shurtu-gal commented on src/config/Navigation.js
Shift this to `data` folder.

2024-03-10 13:33 UTC, ashutosh-rath02 commented
Resolve conflicts and add some hover effects to the text and button.

2024-03-10 13:34 UTC, ashutosh-rath02 commented
![image](https://github.com/dscnitrourkela/project-udon/assets/85403534/da8425df-16e2-4e9f-a44d-4184f3f63ff4)
This icon looks way bigger. Decrease size.

2024-03-10 14:13 UTC, Shurtu-gal commented on src/components/shared/NavBar.jsx
> +		<div>
What does this div do?

2024-03-11 06:19 UTC, Shurtu-gal requested changes

2024-03-11 06:19 UTC, Shurtu-gal commented on src/components/shared/NavBar.jsx
> +				className='navbar flex justify-between items-center opacity-53 bg-hard-light bg-center bg-cover h-[73.8px] overflow-hidden pl-10 '
![image](https://github.com/dscnitrourkela/project-udon/assets/100484401/9548d9af-da9e-4440-ac48-03435eb4840b)
Background is going to the back.

2024-03-11 13:59 UTC, Shurtu-gal approved these changes
LGTM :rock:

2024-03-11 13:59 UTC, merged

2024-03-11 14:00 UTC, Shurtu-gal commented
@all-contributors add @anmol5936 for code.